[general]
start_url = "gemini://gemini.circumlunar.space/capcom"
max_width = 200

[colors]
h1 = "#E84F4F"
h2 = "#D23D3D"
h3 = "#B8D68C"
list = "#C71585"
text = "#D7D0C7"
background = "#151515"
[colors.quote]
    foreground="#e4e4e4"
    background="#404040"

[characters]
list = "🌼 "

[fonts]
[fonts.finger]
    family = "monospace"
    size = 11
[fonts.gemini.text]
    family = "serif"
    size = 11
[fonts.gemini.h1]
    family = "sans"
    size = 16
    style = "normal"
[fonts.gemini.h2]
    family = "monospace"
    size = 13
    style = "italic"
[fonts.gemini.h3]
    family = "monospace"
    size = 12
[fonts.gemini.list]
    family = "sans"
    size = 11
    style = "oblique"
[fonts.gemini.quote]
    family = "sans"
    size = 10
    style = "italic"
[fonts.gopher]
    family = "monospace"
    size = 11
