set -g default-terminal "tmux-256color"
set-option -g focus-events on
set-option -sa terminal-overrides ',xterm-256color:RGB'

# turn on mouse support
set-option -g mouse on
set -g @scroll-speed-num-lines-per-scroll "1"

# update prefix hotkey
set -g prefix C-Space
set -g prefix2 C-b
bind C-Space send-prefix

# panes
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind x kill-pane

bind -n C-M-Left select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up select-pane -U
bind -n C-M-Down select-pane -D

bind -n C-M-S-Left resize-pane -L 5
bind -n C-M-S-Down resize-pane -D 5
bind -n C-M-S-Up resize-pane -U 5
bind -n C-M-S-Right resize-pane -R 5

# windows
bind r command-prompt -I "#W" "rename-window -- '%%'"
bind c new-window -c "#{pane_current_path}"
bind k kill-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status
bind-key -n S-Left previous-window
bind-key -n S-Right next-window


# session
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind C new-session -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n

# window base index
set -g base-index 1

# easy config reload
bind-key X source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."


# buffer mode
setw -g mode-keys vi

# copy and paste
set-option -s set-clipboard off
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'

set-window-option -g xterm-keys on


# style
set-option -g status-position bottom
set -g status-justify centre
set-option -g status-style fg=colour255,bg=default
set-window-option -g window-status-style fg="#666666",bg=default
set-window-option -g window-status-current-style fg=colour1,bg=default

set-option -g message-style fg=colour255,bg=colour8,bright
set -g status-left " "

setw -g window-status-format         ' #(echo "#{pane_current_command}") '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right " "

# escape time 
set-option -sg escape-time 10

